spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5435/salleDb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  documents:
    storage-dir: "/var/app/salle/documents"  # <-- dossier externe prod
