spring:
  application:
    name: salle
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true

app:
  documents:
    # liste de domaines autoris√©s (anti-SSRF)
    allowed-url-hosts:
      - sharepoint.com
      - yourtenant.sharepoint.com
