spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5435/salleDb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.access: TRACE
    org.springframework.security.authentication: TRACE